### ISSUE TITLE
Use syntactic sugar to simplify if statements for burst locations

### ISSUE THREAD

**Issue by smooresni** [NISystemsEngineering/rfic-reference-design-libraries-csharp#30]
![Annotation 2019-07-17 114150](https://user-images.githubusercontent.com/51342134/61394023-e191f080-a887-11e9-9fad-571bde2acb61.png)

**Comment by mdwhitten** [comment]
Beautiful!

**Comment by mdwhitten** [comment]
Fixed in 476d3426dab68dc7cdd04db6ae5df47725688388
