### ISSUE TITLE
Add case in ConfigureInstrument in SG for disabling LO sharing

### ISSUE THREAD

**Issue by mdwhitten** [NISystemsEngineering/rfic-reference-design-libraries-csharp#32]
where is the else case?! what happens if i want to disable LO sharing after I configured it to share the LOs once before

_Originally posted by @smooresni in https://github.com/NISystemsEngineering/rfic-reference-design-libraries-csharp/pull/26_

**Comment by smooresni** [comment]
Resolved in #26
