### ISSUE TITLE
Normalize waveform method needs to be adjusted for waveforms with multiple bursts

### ISSUE THREAD

**Issue by mdwhitten** [NISystemsEngineering/rfic-reference-design-libraries-csharp#33]
_Originally posted by @smooresni in https://github.com/NISystemsEngineering/rfic-reference-design-libraries-csharp/pull/26#issuecomment-512338586_

**Comment by smooresni** [comment]
Submitted pull request #38

**Comment by mdwhitten** [comment]
Fixed in #38
