### ISSUE TITLE
Port LTE module to C# codebase

### ISSUE THREAD

**Issue by mdwhitten** [NISystemsEngineering/rfic-reference-design-libraries-csharp#36]
This feature is implementing the [existing LTE module](https://github.com/NISystemsEngineering/rfic-reference-design-libraries-labview/tree/master/Source/SA/RFmxLTE) in C#.

**Comment by mdwhitten** [comment]
@smooresni Are you interested in tackling this sometime when you return?

**Comment by smooresni** [comment]
@mdwhitten sure thing
