### ISSUE TITLE
Instrument specific configuration per measurement is causing issues for customers

### ISSUE THREAD

**Issue by smooresni** [NISystemsEngineering/rfic-reference-design-libraries-csharp#39]
At a customer site using the RDLs, issues are arising around instrument specific configurations per measurement. Prime example is Reference Clock Source. The instrument ends up taking the reference clock source of the last measurement to call ConfigureCommon(). Customers have to be extra careful about which common configuration gets configured last, or they have to make sure the same reference clock source is chosen in both common configs.

**Comment by mdwhitten** [comment]
Hey @smooresni,

Sorry I didn’t see this. Turns out my notifications weren’t on. 

I am still not sure that I understand the issue that you were observing. Is it that the common configuration was being called for multiple RFmx personalities and ending up with conflicting settings?

**Comment by smooresni** [comment]
Update: Considering addition of Instr specific static methods

**Comment by mdwhitten** [comment]
Addition of Common library in #77 resolves this.

**Comment by smooresni** [comment]
Reopening until we move reference clock into instrument configs
