### ISSUE TITLE
Add DPD  Class

### ISSUE THREAD

**Issue by cindyxie** [NISystemsEngineering/rfic-reference-design-libraries-csharp#50]

**Comment by mdwhitten** [comment]
Hey @heyItsDale my understanding was that all of the DPD functions would live in a separate DPD class; in this way, RFmx DPD & NanoSemi DPD would live within the same class. Is this what you were intending? Did you have a different plan here or share this understanding? I want to make sure that I am on the same page as you and @cindyxie .

**Comment by heyItsDale** [comment]
I haven't discussed this specifically with @cindyxie, but I do think having DPD in a separate class is a good idea. It breaks from RFmx's way of organizing things, but since we want to support alternate methods for DPD I think it makes the most sense.

**Comment by cindyxie** [comment]
@heyItsDale @mdwhitten  Agree.
