### ISSUE TITLE
Add idle duration present to SG Waveform struct

### ISSUE THREAD

**Issue by mdwhitten** [NISystemsEngineering/rfic-reference-design-libraries-csharp#55]
Port the **Idle Duration Present?** property from LabVIEW to the Waveform struct in C# to enable DPD.

FYI @cindyxie

**Comment by mdwhitten** [comment]
@smooresni You have been the SG module guru as of late. Do you have availability/interest to tackle this? Could probably go in with your other open pull request since it would be a "parity" feature.

**Comment by smooresni** [comment]
@mdwhitten yes. i haven't looked but this may have greater impact on the overall sg module

**Comment by mdwhitten** [comment]
Completed in 8ea40fe6e9c11b57aaa25778b20a486607652638
