### ISSUE TITLE
Update SG code to reflect exclusive nature of burst stop locations

### ISSUE THREAD

**Issue by smooresni** [NISystemsEngineering/rfic-reference-design-libraries-csharp#72]
After a recent investigation I've found that waveform burst stop locations are exclusive. This makes burst lengths (in samples) easy to calculate since it's just stopLocation - startLocation. I'd like for us to update the SG module to match this behavior.

**Comment by smooresni** [comment]
Looking into this more, the behavior is inconsistent. Filing a CAR with NI R&D.

**Comment by mdwhitten** [comment]
Does this still need any action?
