### ISSUE TITLE
Regex for getting signal strings needs to be removed from LTE

### ISSUE THREAD

**Issue by smooresni** [NISystemsEngineering/rfic-reference-design-libraries-csharp#76]
LTE still uses the following line of code that needs to be removed:

`string signalString = Regex.Match(selectorString, "signal::[^/]*").Value; // get the signal string`

**Comment by bbachmanNI** [comment]
In the LV implementation after the regex match, there is a call to buildoffsetstring which is passed into GetOffsetFrequency/GetOffsetIntegrationBandwidth
