### ISSUE TITLE
Investigate handling of Auto Level functionality

### ISSUE THREAD

**Issue by mdwhitten** [NISystemsEngineering/rfic-reference-design-libraries-csharp#83]
Auto Level for RFmx is currently implemented in the `Configure Common` function per personality. However, @smooresni has mentioned that this may not work correctly if the personality or channel bandwidth has not yet been configured. Currently, the signal bandwidth is typically configured later on in a `Configure Signal` function. We need to determine if this is a problem.

## Proposals (If Issue Exists)
- Configure the maximum channel bandwidth when auto level is called
   - **Risk:** This may set the reference level higher than required due to other spectral content or noise, affecting EVM
- Creating an RFmx ~~Initialize~~ Initiate function that includes an auto detect optional input
    - **Risk:** This will not work for WLAN, because prior to calling the Auto Detect you must set the reference level. The help suggests calling the Auto Level function first, which suggests that setting the bandwidth correctly first might not be a problem after all.

## Items to Investigate
- [ ] Result of calling Auto Level before channel is properly configured for different WLAN & NR configurations
- [ ] Result of setting maximum bandwidth configuration prior to calling Auto Level

**Comment by smooresni** [comment]
A few more options:
- If RFmx requires the Reference Level be set before the Auto Detect function is called, can we open the reference level all the way up (to say 30dBm) and still successfully auto-detect the signal? After auto-detection we can Auto-level if this works.
- We "servo" the autodetection at the expense of test time. Set the signal bandwidth to 180MHz and autolevel. Then do an auto-detect. Once the standard is detected, auto-level again with the detected bandwidth.
